# Generated by Django 4.0.5 on 2022-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(choices=[('0', 'Fuck NO!'), ('1', 'Horrible'), ('2', 'Terrible'), ('3', 'Lousy'), ('4', 'Crummy'), ('5', 'OK'), ('6', 'Pretty Good'), ('7', 'Good'), ('8', 'Great'), ('9', 'Excellent'), ('10', 'Fabulous')])),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('movies', models.ManyToManyField(related_name='actors', to='movies_app.movie')),
            ],
        ),
    ]
