# Generated by Django 4.0.5 on 2022-06-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[('0', 'Fuck NO!'), ('1', 'Horrible'), ('2', 'Terrible'), ('3', 'Lousy'), ('4', 'Crummy'), ('5', 'OK'), ('6', 'Pretty Good'), ('7', 'Good'), ('8', 'Great'), ('9', 'Excellent'), ('10', 'Fabulous')], db_index=True),
        ),
    ]
