# Generated by Django 4.0.5 on 2022-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
    ]
