# Generated by Django 4.0.5 on 2022-06-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_auth', '0002_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(help_text='We need it to show you relevant content', null=True, verbose_name='Date of Birth'),
        ),
    ]
